### ISSUE TITLE
prepme.bat is not updated on cloudplatformsstreaming.blob.core.windows.net

### ISSUE THREAD

**Issue by blues-man** [cloud-platforms-streaming/azure-obs-vm#7]
The VM created with `build_vm.sh` points to an outdated version of `prepme.bat` which is invoking `vac462.exe` instead of `vac462full.exe` and this generates an error when running the BAT script.

https://github.com/cloud-platforms-streaming/azure-obs-vm/blob/main/prepme.bat#L1

**Comment by chris-short** [comment]
We've tried at several points to automate this but, it seems to be just outside of capable.

The fix here is to write the docs to do those steps manually.

**Comment by chris-short** [comment]
PR #8 resolves this.
